### ISSUE TITLE
redis连接异常

### ISSUE THREAD

**Issue by smallhorsegg** [douban/charts#32]
![image](https://user-images.githubusercontent.com/49267785/185033707-6dbdb897-a8fe-49dc-a4cc-359ed7abfbc4.png)

手动在pod中连接都正常
![image](https://user-images.githubusercontent.com/49267785/185033860-ab2238fb-55eb-4d54-9efb-b5db4b4faf43.png)

env:

             - name: CACHE_URL
              value: 'redis://root:xxxxxxxx@archery-redis-master:6379/0'
            - name: DINGDING_CACHE_URL
              value: 'redis://root:xxxxxxxx@archery-redis-master:6379/1'

**Comment by smallhorsegg** [comment]
这个不能加账号，应该为redis://archery-redis-master:6379/0

**Comment by LeoQuote** [comment]
你好, 这个配置如何填写和 chart 无关, 你需要参考 https://github.com/hhyo/Archery/discussions/1746 这里来写
