### ISSUE TITLE
init failed after installed by helm in k8s 

### ISSUE THREAD

**Issue by wqbbs911** [douban/charts#59]
used helm to install archey with  default vaules.yaml , archey pod failed to running , it :
![image](https://github.com/douban/charts/assets/30170870/7d50c054-e62b-413b-a12b-38f616a60372)

and i also tried to use external mysql ,got same issue:

![image](https://github.com/douban/charts/assets/30170870/a5b322a1-a810-46f1-8d83-34f1153cab42)

and no more logs, how to debug or fix it ? thanks very much!!

**Comment by LeoQuote** [comment]
你好, 操作 k8s 需要一定的基础知识, 如果你连 podInitilizing 都不知道怎么处理, 那代表你知识还需要更新, 可以自行搜索学习一下, 
此 issue 和 archery 和 helm chart 均无关系, closing
