### ISSUE TITLE
Archery 对接 LDAP

### ISSUE THREAD

**Issue by mcboyz** [douban/charts#60]
您好 ，我正在使用Helm部署Archery ，其它的配置一切就绪了
现在想接入我的LDAP，遇到问题
可以帮忙看看吗

报错如下图：
<img width="708" alt="error" src="https://github.com/douban/charts/assets/101558829/5ee78821-4577-43f6-9ecd-ea73e2521274">

[MainThread:140672976959296][task_id:django_auth_ldap][config.py:155][ERROR]- search_s('dc=unilever-china,dc=azure', 2, '(uid=liutao2_app)') raised OPERATIONS_ERROR({'msgtype': 115, 'msgid': 2, 'result': 1, 'desc': 'Operations error', 'ctrls': [], 'info': '000004DC: LdapErr: DSID-0C090CF4, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4563'})

value.yaml中的相关配置如下：
envs:
  - name: DEBUG
    value: "True"
  - name: CSRF_TRUSTED_ORIGINS
    value: "https://archery-devops.test.com,http://archery-devops.test.com"
  - name: ENABLE_LDAP
    value: "true"
  - name: AUTH_LDAP_ALWAYS_UPDATE_USER
    value: "true"
  - name: AUTH_LDAP_SERVER_URI
    value: "ldap://10.20.x.x:389"
  - name: AUTH_LDAP_BIND_DN
    value: "CN=devops_ldap,OU=ladp_account,OU=xx1,OU=xx2,DC=test,DC=com"
  - name: AUTH_LDAP_BIND_PASSWORD
    value: "xxxxx"
  - name: AUTH_LDAP_USER_SEARCH_BASE
    value: "dc=test,dc=com"
  - name: AUTH_LDAP_USER_SEARCH_FILTER
    value: "(uid=%(user)s)"
  - name: AUTH_LDAP_USER_ATTR_MAP
    value: "username=sAMAccountname,display=displayName,email=mail,first_name=givenName,last_name=sn"

**Comment by LeoQuote** [comment]
和helm chart 不相关，请自行解决或咨询 archery项目
