### ISSUE TITLE
考虑升级下dify charts中的minio、redis等的版本否

### ISSUE THREAD

**Issue by jeessy2** [douban/charts#76]

**Comment by LeoQuote** [comment]
欢迎 pr, chart 中自带的 minio, redis pg 等都不建议使用, 只是用于实验, 默认配置是无持久卷的, 在 readme 中也是建议用外部资源

**Comment by LeoQuote** [comment]
我建议不加, 因为需要加持久卷的, 又有一些说明要写, storageclass 之类的, 包括你用本地卷什么的都是一堆事, 这样你默认配置反而就不能一键启动了. 

你想做的话, 我建议只写在Readme 里, 或者说你提供一个 values-with-persistence.yaml 也可以. 我个人观点是这个配置绝对够实验, 你就不要重启或者删除 pod 就没事了, 我承认这可能会有一些风险, 比如有的人就忘了这事, 但是这也没办法...

**Comment by jeessy2** [comment]
确实容易忘了，如果不仔细看文档的话。bitnami默认就是true,结果这边默认false了...
