### ISSUE TITLE
[GoInception] Failed to install goinception pod in my k8s in China region

### ISSUE THREAD

**Issue by visla-xugeng** [douban/charts#92]
**Describe the bug**
I cannot pull the image, busybox from docker hub since the installation of goinception is located in China region. As a result, the installation of the pod failed. (I tried to install the chart, Archery, also failed since the goinception is dependent part in the chart. )

I checked the deployment of goinception(see link below).  The address of busybox is hard coded. Can someone in team change it to an variable? Then I can modify the value to a local repo in China region instead of pointing to the docker hub directly. 

https://github.com/douban/charts/blob/3fa7828ca90be5e317e4a6c4ab9ca762e636e9df/charts/goinception/templates/deployment.yaml#L31

**To Reproduce**
Follow the https://github.com/douban/charts/tree/master/charts/archery
to install the Archery chart in China region, you will see the issue. 

**Expected behavior**
Want to install the goinception pod in China region successfully.

**Screenshots**

**Additional context**

**Comment by LeoQuote** [comment]
欢迎pr，另外，你可以使用containerd 的 registry mirror https://github.com/containerd/containerd/blob/main/docs/cri/registry.md

或者k8s 的mutation webhook 解决问题 https://open-policy-agent.github.io/gatekeeper/website/docs/mutation/ https://kyverno.io/docs/writing-policies/mutate/

**Comment by visla-xugeng** [comment]
Thank you so much. Just did a quick change and sent a PR. Please help check.
